function CVPlot(cdata1)
%CREATEFIGURE(cdata1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 14-Jun-2018 23:00:33

% Create figure
figure1 = figure;
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image([-5 -3 -1 1 3 5 7 9],[-10 -8 -6 -4 -2 0 2 4],cdata1,'Parent',axes1,...
    'CDataMapping','scaled');

% Create ylabel
ylabel('log2 gamma');

% Create xlabel
xlabel('log2 ');

% Create title
title('A3 versus Rest 10 -fold Cross Validation');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-11 5]);
% Set the remaining axes properties
set(axes1,'XTick',[-5 -3 -1 1 3 5 7 9],'XTickLabel',...
    {'-5','-3','-2','0','2','4','6','8'},'YTick',[-10 -8 -6 -4 -2 0 2 4]);
% Create colorbar
colorbar('peer',axes1);

